Page Title: Bill And Usage Page

#Object Definitions
==================================================================================================================================
expandMibileBillDetails					xpath		(//XCUIElementTypeOther[@name=""])[2]
billingSummarySectionHeader				xpath		//XCUIElementTypeStaticText[@name='Billing Summary']
currentPlanName							xpath		//XCUIElementTypeStaticText[@name="4G Super Smart 899"]
extraPackagesText						xpath		//XCUIElementTypeStaticText[@name="(4 Extra Packages)"]
currentUsageTab							xpath		//XCUIElementTypeOther[@name="Current Usage "]
billDetailsTab							xpath		//XCUIElementTypeOther[@name="Bill Details"]
billDetails_ViewPaymentHistoryLink		xpath		//XCUIElementTypeOther[@name="View payment history"]
currentUsage_talk						xpath		//XCUIElementTypeOther[@name="Talk 50 from 80 min"]
currentUsage_data						xpath		//XCUIElementTypeOther[@name="Data 20 from 100 GB"]
currentUsage_buyExtraPackPopuUpHeader	xpath		//XCUIElementTypeStaticText[@name="Buy extra price packs!"]
currentUsage_seeOtherExtraPackages		xpath		//XCUIElementTypeOther[@name="See other extra packages"]
currentUsage_sharedNumbersLink			xpath		//XCUIElementTypeOther[@name="Shared numbers 2 "]
search_CurrentPlanDetailsIcon			xpath		//XCUIElementTypeOther[@name=""]
packageDetailsTab						xpath		//XCUIElementTypeOther[@name="Package Detail "]
packageDetails_voiceLabel				xpath		//XCUIElementTypeStaticText[@name="Voice"]
packageDetails_dataLabel				xpath		//XCUIElementTypeStaticText[@name="Data"]
packageDetails_wifiLabel				xpath		//XCUIElementTypeStaticText[@name="Free WIFI"]
packageDetails_smsMmsLabel				xpath		//XCUIElementTypeStaticText[@name="SMS/MMS"]
extraPackageTab							xpath		//XCUIElementTypeOther[@name="Extra Package"]
extraPackage_activeSection              xpath		//XCUIElementTypeStaticText[@name="Active"]
extraPackage_inActiveSection			xpath		//XCUIElementTypeStaticText[@name="Inactive"]
billDetails_pendingBill1                xpath       (//XCUIElementTypeOther[@name="฿ 181 .29"])[2]
